### ISSUE TITLE
Can't compile on linux ubuntu 12.04 

### ISSUE THREAD

**Issue by AndreFaramir** [hjnilsson/rme#25]
Errors while trying to compile

[  1%] Building CXX object CMakeFiles/rme.dir/source/about_window.cpp.o
In file included from /home/andre/Desktop/Projetos/remeres/source/json/json_spirit_reader.h:14:0,
                 from /home/andre/Desktop/Projetos/remeres/source/json/json_spirit.h:14,
                 from /home/andre/Desktop/Projetos/remeres/source/json.h:10,
                 from /home/andre/Desktop/Projetos/remeres/source/main.h:126,
                 from /home/andre/Desktop/Projetos/remeres/source/about_window.cpp:20:
/home/andre/Desktop/Projetos/remeres/source/json/json_spirit_error_position.h:21:12: error: looser throw specifier for ‘virtual json_spirit::Error_position::~Error_position()’
/usr/include/c++/4.6/stdexcept:122:13: error:   overriding ‘virtual std::runtime_error::~runtime_error() throw ()’
make[2]: *** [CMakeFiles/rme.dir/source/about_window.cpp.o] Error 1
make[1]: *** [CMakeFiles/rme.dir/all] Error 2
make: *** [all] Error 2

**Comment by paulohsms1** [comment]
I am also having this problem:

CMakeFiles/rme.dir/build.make:57: recipe for target 'CMakeFiles/rme.dir/source/about_window.cpp.o' failed
make[2]: *** [CMakeFiles/rme.dir/source/about_window.cpp.o] Error 1
CMakeFiles/Makefile2:63: recipe for target 'CMakeFiles/rme.dir/all' failed
make[1]: *** [CMakeFiles/rme.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2

would you please help?

**Comment by gpedro** [comment]
please, checkout latest version and try again.
