### ISSUE TITLE
Wxwidgets 3.1 errors

### ISSUE THREAD

**Issue by comedinha** [hjnilsson/rme#112]
I try build with wx 3.1 and give errors of the wx update...

(MSVC 14.0 and Boost 1.60)

Only have erros with SetCellValue
```
1>------ Build started: Project: RME, Configuration: Beta Release x64 ------
1>  live_tab.cpp
1>..\..\source\live_tab.cpp(153): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'wxString' to 'int'
1>  ..\..\source\live_tab.cpp(153): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\source\live_tab.cpp(154): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'wxString' to 'int'
1>  ..\..\source\live_tab.cpp(154): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\source\live_tab.cpp(155): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'const wxString' to 'int'
1>  ..\..\source\live_tab.cpp(155): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\source\live_tab.cpp(168): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'wxString' to 'int'
1>  ..\..\source\live_tab.cpp(168): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\source\live_tab.cpp(169): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'const wxString' to 'int'
1>  ..\..\source\live_tab.cpp(169): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\source\live_tab.cpp(170): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'const wxString' to 'int'
1>  ..\..\source\live_tab.cpp(170): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\source\live_tab.cpp(210): error C2664: 'void wxGrid::SetCellBackgroundColour(int,int,const wxColour &)': cannot convert argument 1 from 'wxColour' to 'int'
1>  ..\..\source\live_tab.cpp(210): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\source\live_tab.cpp(211): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'wxString' to 'int'
1>  ..\..\source\live_tab.cpp(211): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\source\live_tab.cpp(212): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'wxString' to 'int'
1>  ..\..\source\live_tab.cpp(212): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>  properties_window.cpp
1>..\..\source\properties_window.cpp(171): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'std::string' to 'int'
1>  ..\..\source\properties_window.cpp(171): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\source\properties_window.cpp(174): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'const wchar_t [7]' to 'int'
1>  ..\..\source\properties_window.cpp(174): note: There is no context in which this conversion is possible
1>..\..\source\properties_window.cpp(175): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'wxString' to 'int'
1>  ..\..\source\properties_window.cpp(175): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\source\properties_window.cpp(179): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'const wchar_t [7]' to 'int'
1>  ..\..\source\properties_window.cpp(179): note: There is no context in which this conversion is possible
1>..\..\source\properties_window.cpp(180): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'wxString' to 'int'
1>  ..\..\source\properties_window.cpp(180): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\source\properties_window.cpp(186): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'const wchar_t [6]' to 'int'
1>  ..\..\source\properties_window.cpp(186): note: There is no context in which this conversion is possible
1>..\..\source\properties_window.cpp(189): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'wxString' to 'int'
1>  ..\..\source\properties_window.cpp(189): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\source\properties_window.cpp(194): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'const wchar_t [8]' to 'int'
1>  ..\..\source\properties_window.cpp(194): note: There is no context in which this conversion is possible
1>..\..\source\properties_window.cpp(195): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'const wchar_t *' to 'int'
1>  ..\..\source\properties_window.cpp(195): note: There is no context in which this conversion is possible
1>..\..\source\properties_window.cpp(201): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'const wchar_t [8]' to 'int'
1>  ..\..\source\properties_window.cpp(201): note: There is no context in which this conversion is possible
1>..\..\source\properties_window.cpp(202): error C2664: 'void wxGrid::SetCellBackgroundColour(int,int,const wxColour &)': cannot convert argument 1 from 'const wxColour' to 'int'
1>  ..\..\source\properties_window.cpp(202): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\source\properties_window.cpp(203): error C2664: 'void wxGrid::SetCellBackgroundColour(int,int,const wxColour &)': cannot convert argument 1 from 'const wxColour' to 'int'
1>  ..\..\source\properties_window.cpp(203): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by comedinha** [comment]
To fix: Change SetCellValue(str, int, int) to SetCellValue(int, int, str)

Exemple:
```
grid->SetCellValue(wxT("String"), rowIndex, 1);
grid->SetCellValue(wxstr(*attr.getString()), rowIndex, 2);
```

To
```
grid->SetCellValue(rowIndex, 1, wxT("String"));
grid->SetCellValue(rowIndex, 2, wxstr(*attr.getString()));
```

**Comment by gpedro** [comment]
we will be grateful if you would send us a pull request (:

**Comment by comedinha** [comment]
OK :3

**Comment by gpedro** [comment]
Thanks for contribution <3
